platform [marvell] prestera boot distinct mmcblk vs scsi
Why I did it
AC5P-RD (arm64-marvell_rd98DX45xx_cn9131-r0) may have
disk scsi or mmcblk, but only scsi is handled.
On the "sonic-installer install" action the blk_dev is empty
instead of "blk_dev=/dev/mmcblk0"
leading to wrong Uboot env parameters
  sonic_boot_load= ... mmc 0: ...
  sonic_boot_load_old= ... mmc 0: ...
instead of correct "mmc 0:2"
The further reboot fails with
  Wrong Image Format for bootm command
  ERROR: can't get kernel image!

How I did it
Add mmc_bus="mmc0:0001" and use in get_install_device()
as last default.

How to test
sonic-installer install sonic-marvell-prestera-arm64.bin; reboot

Signed-off-by: Yan Markman <ymarkman@marvell.com>